# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
src/generic
src/reflect
)

#
# contents selected with patternfile ??-header--private-headers
#
set( PRIVATE_HEADERS
src/generic/include-private.h
src/reflect/_mulle-objc-debug-include-private.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/c-set.inc
src/generic/include.h
src/mulle-objc-debug.h
src/mulle-objc-dotdump.h
src/mulle-objc-htmldump.h
src/mulle-objc-html.h
src/mulle-objc-typeinfodump.h
src/reflect/_mulle-objc-debug-include.h
src/reflect/_mulle-objc-debug-versioncheck.h
)

