# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/mulle-objc-dotdump.c
src/mulle-objc-gdb.c
src/mulle-objc-html.c
src/mulle-objc-htmldump.c
src/mulle-objc-lldb.c
src/mulle-objc-typeinfodump.c
)
