/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_debug_include_h__
#define _mulle_objc_debug_include_h__

// You can tweak the following #include with these commands.
// (Use 816D910C-5462-4079-83F7-6E3223DFF075 instead of mulle-fprintf if there are duplicate entries)
//    remove:             `mulle-sde dependency mark mulle-fprintf no-header`
//    rename:             `mulle-sde dependency|library set mulle-fprintf include whatever.h`
//    reorder:            `mulle-sde dependency move mulle-fprintf <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-fprintf [no-]import`
//    toggle public:      `mulle-sde dependency mark mulle-fprintf [no-]public`
//    toggle optional:    `mulle-sde dependency mark mulle-fprintf [no-]require`
//    remove for platform:`mulle-sde dependency mark mulle-fprintf no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-fprintf/mulle-fprintf.h>   // mulle-fprintf

#endif
