/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_debug_include_private_h__
#define _mulle_objc_debug_include_private_h__

// You can tweak the following #include with these commands.
// (Use 1CBD88F9-8E8E-4448-A604-B26569445FFE instead of mulle-objc-runtime if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-objc-runtime no-header`
//    rename:              `mulle-sde dependency|library set mulle-objc-runtime include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-objc-runtime <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-objc-runtime [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-objc-runtime [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-objc-runtime [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-objc-runtime no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-objc-runtime/mulle-objc-runtime.h>   // mulle-objc-runtime

#endif
