/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_debug_include_private_h__
#define _mulle_objc_debug_include_private_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-objc-runtime`
// (Use 440E8246-6A2F-45E8-AC96-A2D94DD3285E instead of mulle-objc-runtime, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-objc-runtime no-header`
//    rename              : `mulle-sde dependency|library set mulle-objc-runtime include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-objc-runtime <up|down>`
//    toggle objc         : `mulle-sde dependency mark mulle-objc-runtime [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-objc-runtime [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-objc-runtime [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-objc-runtime no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-objc-runtime/mulle-objc-runtime.h>   // mulle-objc-runtime

#endif
